# -*- coding: utf-8 -*-
"""desafio_scraping_bitcoin_dolar_alunos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nmCv1SVrDx1dcmd-FRk_mZid9T6zPft

PRÁTICA - BITCOIN & DOLAR
"""

#!pip install requests

#!pip freeze

import requests
import re

"""### scraping da página bitcoin"""

x = requests.get('https://dolarhoje.com/bitcoin-hoje/')
print(x.status_code)
conteudo = x.content

#buscar ponto inicial

#buscar ponto final

#capturar trecho de interesse
trecho = str(conteudo)[:]
trecho

"""### cotação bitcoin"""

cotacao_btc = re.search("", trecho)
type(cotacao_btc)

cotacao_btc

cotacao_btc.group(1)

# substituição de vírgula para ponto
valor_btc =
# conversão da cotação bitcoin de string para numérica
valor_btc =
# definição das casas decimais
valor_btc =
# exibição da varíavel
valor_btc

"""### scraping da página dolar"""

x = requests.get('')
print(x.status_code)
conteudo = x.content

#buscar ponto inicial

#buscar ponto final

#capturar trecho de interesse
trecho = str(conteudo)[:]
trecho

"""### cotação dolar"""

cotacao_dol = re.search("", trecho)
type(cotacao_dol)

cotacao_dol

cotacao_dol.group(1)

# substituição de vírgula para ponto
valor_dol =
# conversão da cotação dolar de string para numérica
valor_dol =
# definição das casas decimais
valor_dol =
# exibição da varíavel
valor_dol

"""### conversão da cotação do bitcoin de reais para dolar"""

btc_dol =

print('1 bitcoin vale USD {}'.)