# -*- coding: utf-8 -*-
"""pratica_beautifulsoup_alunos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzQplUXuixJ80wax12okRygHjZpSRbRv

## PRÁTICA - beautifulsoup
"""

from bs4 import BeautifulSoup
import requests

URL = "https://dolarhoje.com"
page = requests.get(URL)

soup = BeautifulSoup(page.content, "html.parser")
soup

tag = soup.find(id='nacional')
#conversao da string capturada para float
valor = tag['value'].replace(',','.')
valor = float(valor)
#exibicao do valor
valor

round(valor * 5, 2)