# -*- coding: utf-8 -*-
"""pratica_scraping_alunos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeOY7mPR0O2BVguP6QHqOTBCAlGvdM5D

PRÁTICA - web scraping
"""

!pip install requests

!pip freeze

import requests

x = requests.get('https://dolarhoje.com.br')
print(x.status_code)

x.content

x.text

x.text.index('US$')

conteudo = x.content

str(x.content).index('US$')

texto = x.text
posA = texto.find('US$')
posA

texto[posA:]

posB = texto.index('hoje', 3876)
posB

trecho = texto[posA:posB]
trecho

#buscar ponto inicial

#buscar ponto final

#capturar trecho de interesse
trecho = str(conteudo)[:]
trecho

"""##Tratamento"""

conteudo = x.content

str(conteudo).index('US$ 1,00')

str(conteudo).index('\\n', 4273)

trecho = str(conteudo)[4273:4356]
trecho

"""## Biblioteca Regex"""

import re

"""### função sub"""

trecho

cotacao = re.sub(" ", "_", trecho)
type(cotacao)

cotacao

"""### função split"""

cotacao = re.split(" ", trecho)
type(cotacao)

cotacao

"""### função findall"""

cotacao = re.findall(" ", trecho)
type(cotacao)

cotacao

teste = re.findall("R\S.*", "R$ 4,48  R$ 5,32  R$ 45,00  R$ 123,00")
teste

"""### função search"""

cotacao = re.search("R\S (.{4})", trecho)
type(cotacao)

cotacao

cotacao.string

cotacao.span()

cotacao.group()

cotacao.group(1)

valor = cotacao.group(1).replace(',','.')
valor = round(float(valor), 2)
valor

valor * 140

teste = re.search("R\S (.{4})", " R$ 45,00  R$ 4,00  R$ 6,00 ")
teste